### PR TITLE
Fix Unused Attribute Validation Warnings

### LINKED ISSUE #766: Consider Splitting Up MeshVertex

### LINKED ISSUE #888: Address Validation Warnings in CI
We have a lot of warnings around vertex attributes not being consumed.

```
Validation Performance Warning: [ UNASSIGNED-CoreValidation-Shader-OutputNotConsumed ] Object 0: handle = 0xd27c3e0000000123, name = PostProcess.vsh, type = VK_OBJECT_TYPE_SHADER_MODULE; | MessageID = 0x609a13b | vkCreateGraphicsPipelines(): pCreate
Infos[0] Vertex attribute at location 5 not consumed by vertex shader
                 Object[0] (shader module): Handle 0xd27c3e0000000123, Name: 'PostProcess.vsh'
W [Diligent] Vulkan debug message (performance): UNASSIGNED-CoreValidation-Shader-OutputNotConsumed
                 Validation Performance Warning: [ UNASSIGNED-CoreValidation-Shader-OutputNotConsumed ] Object 0: handle = 0xd27c3e0000000123, name = PostProcess.vsh, type = VK_OBJECT_TYPE_SHADER_MODULE; | MessageID = 0x609a13b | vkCreateGraphicsPipelines(): pCreateInfos[0] Vertex attribute at location 6 not consumed by vertex shader
                 Object[0] (shader module): Handle 0xd27c3e0000000123, Name: 'PostProcess.vsh'```

### PR DESCRIPTION
**Pull request by McCallisterRomer**
resolves #766, resolves #888

Updating input layouts to only include required attributes. Fixes 'OutputNotConsumed' warnings. Also removing tangents/bitangents from mesh assets.

### CODE REVIEW

File: source/ncconvert/converters/GeometryConverter.cpp [hunk 1]
```diff
@@ -335,25 +333,35 @@ auto ConvertToMeshVertices(const aiMesh* mesh) -> std::vector<nc::asset::MeshVer
...
+                boneData.boneIds
             );
         }
         return out;
     }
 
     for (auto i = 0u; i < nVertices; ++i)
     {
-        const auto uv = mesh->mTextureCoords[0][i];
+        const auto& uv = mesh->mTextureCoords[0][i];
```
Comment (jaremieromer) [inline source/ncconvert/converters/GeometryConverter.cpp:358]: nice

**Review by jaremieromer — APPROVED** [review]
